name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: yarn -s || echo "Done"
      - run: yarn build-app
      - name: Checkout build branch in .build-branch
        uses: actions/checkout@v2
        with:
          ref: build
          path: .build-branch
      - name: Copy new build files into .build-branch
        run: cp -r ./build/* ./.build-branch
      - name: Commit & Push changes in the .build-branch
        run: |
          last_commit=`git log --pretty=%s -1` && echo $last_commit
          cd .build-branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploying code: $last_commit" || echo "Ignoring nothing to commit"
          git push origin build
